// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/atakum-home/Hiz.tsx": () => import("../components/mockups/atakum-home/Hiz.tsx"),
  "./components/mockups/atakum-home/Sicak.tsx": () => import("../components/mockups/atakum-home/Sicak.tsx"),
  "./components/mockups/atakum-home/Vitrin.tsx": () => import("../components/mockups/atakum-home/Vitrin.tsx"),
  "./components/mockups/homepage-2026/Modern.tsx": () => import("../components/mockups/homepage-2026/Modern.tsx"),
  "./components/mockups/jetgo-landing/Landing.tsx": () => import("../components/mockups/jetgo-landing/Landing.tsx"),
  "./components/mockups/jetgo-landing/Variant2.tsx": () => import("../components/mockups/jetgo-landing/Variant2.tsx"),
  "./components/mockups/yourpoodle/Bilgi.tsx": () => import("../components/mockups/yourpoodle/Bilgi.tsx"),
  "./components/mockups/yourpoodle/BilgiBankasi.tsx": () => import("../components/mockups/yourpoodle/BilgiBankasi.tsx"),
  "./components/mockups/yourpoodle/Club.tsx": () => import("../components/mockups/yourpoodle/Club.tsx"),
  "./components/mockups/yourpoodle/HomePage.tsx": () => import("../components/mockups/yourpoodle/HomePage.tsx"),
  "./components/mockups/yourpoodle/Homepage.tsx": () => import("../components/mockups/yourpoodle/Homepage.tsx"),
  "./components/mockups/yourpoodle/Magaza.tsx": () => import("../components/mockups/yourpoodle/Magaza.tsx"),
  "./components/mockups/yourpoodle/Rehber.tsx": () => import("../components/mockups/yourpoodle/Rehber.tsx"),
  "./components/mockups/yourpoodle/YourPoodleHome.tsx": () => import("../components/mockups/yourpoodle/YourPoodleHome.tsx")
};
